import * as mongoose from 'mongoose';


export const VoluntarySchema = new mongoose.Schema({
  nome: String,
  typeUser:String,
  dataNascimento: String,
  sexo: String,
  endereco: {
    rua: String,
    numero: String,
    bairro: String,
    cidade: String,
    complemento: String,
    uf: String,
    CEP: String,
  },
  profissao: String,
  telefone: String,
  telefoneFx: String,
  estadoCivil: String,
  email: String,
  password: String,
  nomeIg: String,
  pastor: String,
  typeVoluntary: {
    chekbox1Profissao: Boolean,
    chekbox2Intercessor: Boolean,
    chekbox3Cuidador: Boolean,
    chekbox4CasaDescanso: Boolean,
  },
  chekbox5Aconselhamento: Boolean,
  especialidade: String,
  urlsImage: {
    urlImgPrincipal: String,
    urlImgCasaDescansoPrincipal: String,
    urlImgsCasaDescanso: [],
  },
  servicoOferecido: String,
  dataCad: String,
  status: String,
  localDescanso: {
    typeLocalDescanso: {
      casaDePraia: Boolean,
      casaDeCampo: Boolean,
      pousada: Boolean,
      hotel: Boolean,
      outros: Boolean,
    },
    nomeLocalDescanso: String,
    CNPJLocalDescanso: String,
    enderecoLocalDescanso: {
      ruaLocalDescanso: String,
      numeroLocalDescanso: String,
      complementoLocalDescanso: String,
      CEPLocalDescanso: String,
      bairroLocalDescanso: String,
      cidadeLocalDescanso: String,
      ufLocalDescanso: String,
    },
    disponibilidadeDuranteAno: Boolean,
    mesesNaoDisponivel: String,
    mesesNaoDisponivelDescrito: String,
    maximoDiariaPg: String,
    maximoHospedesPorVez: String,
    qtFamiliaMes: String,
    custoHospedagem: String,
    valorHospedagem: String,
    alimentacao: Boolean,
    custoAlimentacao: String,
    valorRefeicoes: String,
    roupaCama: Boolean,
    qtQuartos: String,
    qtSuites: String,
    qtCamasCasal: String,
    qtCamasSolteiro: String,
    servicosDisponibilizados: {
      piscina: Boolean,
      quadra: Boolean,
      restaurante: Boolean,
      TV: Boolean,
      internet: Boolean,
      garagem: Boolean,
      outrosServicosOferecidos: Boolean,
      outrosServicosOferecidosDescrito: String,
    },
  },
});
